<?php
/**
 * @file
 * Code for the Google CSE Admin feature.
 */

include_once 'cu_google_cse_admin_bundle.features.inc';

/**
 * Implements hook_secure_permissions().
 *
 * Adding permissions for google cse admin.
 */
function cu_google_cse_admin_bundle_secure_permissions($role) {
  $permissions = array(
    'administrator' => array(
      'create cu_google_cse content',
      'edit own cu_google_cse content',
      'edit any cu_google_cse content',
      'delete own cu_google_cse content',
      'delete any cu_google_cse content',
    ),
    'developer' => array(
      'create cu_google_cse content',
      'edit own cu_google_cse content',
      'edit any cu_google_cse content',
      'delete own cu_google_cse content',
      'delete any cu_google_cse content',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_menu().
 */
function cu_google_cse_admin_bundle_menu() {
  $items = array();

  $items['node/%node/google-cse.xml'] = array(
    'title' => 'Google CSE XML',
    'description' => 'Export custom search engine code',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'cu_google_cse_admin_bundle_render_xml',
    'page arguments' => array(1),
    'access callback' => 'cu_google_cse_admin_bundle_render_xml_access',
    'access arguments' => array(1),
  );
  return $items;
}

///**
// * Returns xml with only the settings in google-cse-xml.tpl
// */
function cu_google_cse_admin_bundle_render_xml($node) {
  print theme('google_cse_xml', array('node' => $node));
}
//
///**
// * Checks content types that configured to allow the nodes be rendered as PBCore xml.
// */
function cu_google_cse_admin_bundle_render_xml_access($node) {

    if ($node->type == 'cu_google_cse') {
      return TRUE;
    }
    return FALSE;
}

/**
 * Implements hook_theme().
 */
function cu_google_cse_admin_bundle_theme() {

  return array(
    'google_cse_xml' => array(
      'template' => 'templates/google-cse-xml',
      'variables' => array('node' => NULL),
    ),
  );
}